"""
Evaluate Rashi Phal Takkar
==========================
Tests the Takkar (1-7 collision) and Nisht Grah (H8) patterns, but strictly scopes them
ONLY to planets identified as "Doubtful Promises" (Rashi Phal) in the Natal chart.
This tests the hypothesis that Takkar is highly predictive when applied only to volatile planets,
eliminating the false positives generated by stable (Grah Phal) planets.
"""

import json
import os
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
_BACKEND = os.path.normpath(os.path.join(_HERE, ".."))
if _BACKEND not in sys.path:
    sys.path.insert(0, _BACKEND)

from astroq.lk_prediction.chart_generator import ChartGenerator
from astroq.lk_prediction.doubtful_timing_engine import DoubtfulTimingEngine

GROUND_TRUTH_PATH = os.path.join(_BACKEND, "data", "public_figures_ground_truth.json")
NOISE_WINDOW = 3

def get_doubtful_planets(natal_chart) -> set:
    """Returns a set of planets involved in Doubtful Natal Promises."""
    engine = DoubtfulTimingEngine()
    promises = engine._identify_doubtful_natal_promises(natal_chart)
    doubtful_planets = set()
    for p in promises:
        for planet in p.get("planets", []):
            doubtful_planets.add(planet)
    return doubtful_planets

def is_rashiphal_takkar(doubtful_planets: set, natal_pos: dict, annual_pos: dict):
    """
    Returns (bool, str) if a Sudden Strike geometry involves a Doubtful planet.
    """
    if not doubtful_planets:
        return False, ""
        
    # 1. Nisht Grah Rule (Doubtful Natal H8 planet moves to Annual H6, H7, H8)
    for planet, n_house in natal_pos.items():
        if planet in doubtful_planets and n_house == 8:
            a_house = annual_pos.get(planet)
            if a_house in [6, 7, 8]:
                return True, f"Nisht Grah: Doubtful {planet} (Natal H8 -> Annual H{a_house})"
                
    # 2. 8th House Malefic Strike (Natal H8 empty, Annual H8 gets a Doubtful malefic)
    natal_h8_empty = not any(h == 8 for p, h in natal_pos.items() if p != "Lagna")
    if natal_h8_empty:
        for malefic in ["Saturn", "Rahu", "Ketu", "Mars"]:
            if malefic in doubtful_planets and annual_pos.get(malefic) == 8:
                return True, f"H8 Strike: Doubtful {malefic} moved into empty H8"
                
    # 3. 1-7 Takkar involving a Doubtful planet
    enemy_pairs = [("Sun", "Saturn"), ("Sun", "Rahu"), ("Moon", "Rahu"), 
                   ("Moon", "Ketu"), ("Jupiter", "Venus"), ("Jupiter", "Rahu")]
    
    h1_planets = [p for p, h in annual_pos.items() if h == 1 and p != "Lagna"]
    h7_planets = [p for p, h in annual_pos.items() if h == 7 and p != "Lagna"]
    
    for p1 in h1_planets:
        for p2 in h7_planets:
            if (p1, p2) in enemy_pairs or (p2, p1) in enemy_pairs:
                if p1 in doubtful_planets or p2 in doubtful_planets:
                    return True, f"Rashi Phal Takkar: Doubtful planet involved in {p1} (H1) vs {p2} (H7)"
                
    return False, ""

def determine_polarity(description: str, domain: str) -> str:
    desc_lower = description.lower()
    malefic_keywords = ["death", "accident", "fired", "divorce", "loss", "cancer", "arrest", "jail", "collapse", "assassination", "resignation"]
    if any(k in desc_lower for k in malefic_keywords) or domain == "health":
        return "Malefic"
    return "Benefic"

def main():
    with open(GROUND_TRUTH_PATH, "r") as f:
        figures = json.load(f)
        
    total_malefic_events = 0
    true_positives = 0
    tp_reasons = []
    
    total_noise_years = 0
    false_positives = 0
    
    print("Evaluating Takkar purely on Rashi Phal (Doubtful) planets...")
    
    for fig in figures:
        name = fig["name"]
        try:
            gen = ChartGenerator()
            place = fig.get("birth_place", "India")
            locations = gen.geocode_place(place)
            if not locations:
                lat, lon, utc = 20.0, 77.0, "+05:30"
            else:
                loc = locations[0]
                lat, lon, utc = loc["latitude"], loc["longitude"], loc["utc_offset"]
                
            natal = gen.generate_chart(fig["dob"], fig.get("tob", "12:00"), place, lat, lon, utc, "vedic")
            n_pos = {p: d["house"] for p, d in natal["planets_in_houses"].items() if p != "Lagna"}
            
            doubtful_planets = get_doubtful_planets(natal)
            # If the figure has no doubtful planets, we still count their events in the denominator
            # to be mathematically rigorous, but they will never trigger a True/False positive here.
            
            all_annual = gen.generate_annual_charts(natal, max_years=100)
            
            for event in fig.get("events", []):
                age = event["age"]
                polarity = determine_polarity(event.get("description", ""), event.get("domain", ""))
                
                if polarity == "Malefic":
                    total_malefic_events += 1
                    annual = all_annual.get(f"chart_{age}")
                    if annual:
                        a_pos = {p: d["house"] for p, d in annual["planets_in_houses"].items() if p != "Lagna"}
                        hit, reason = is_rashiphal_takkar(doubtful_planets, n_pos, a_pos)
                        if hit:
                            true_positives += 1
                            tp_reasons.append(f"{name} (Age {age}): {reason}")
                                
                    # Noise testing
                    for noise_age in range(max(1, age - NOISE_WINDOW), age + NOISE_WINDOW + 1):
                        if noise_age == age:
                            continue
                        n_annual = all_annual.get(f"chart_{noise_age}")
                        if n_annual:
                            total_noise_years += 1
                            na_pos = {p: d["house"] for p, d in n_annual["planets_in_houses"].items() if p != "Lagna"}
                            fp_hit, _ = is_rashiphal_takkar(doubtful_planets, n_pos, na_pos)
                            if fp_hit:
                                false_positives += 1
                                
        except Exception as e:
            continue

    print(f"\n===========================================")
    print(f"Rashi Phal Takkar Evaluation")
    print(f"===========================================")
    print(f"Total Malefic Events Analyzed: {total_malefic_events}")
    print(f"True Positives (Events Caught): {true_positives} ({(true_positives/max(1, total_malefic_events))*100:.1f}%)")
    print(f"Total Noise Years Analyzed: {total_noise_years}")
    print(f"False Positives (Noise Flagged): {false_positives} ({(false_positives/max(1, total_noise_years))*100:.1f}%)")
    print(f"-------------------------------------------")
    print(f"Events successfully caught by Rashi Phal Takkar:")
    for t in tp_reasons:
        print(f"  - {t}")

if __name__ == "__main__":
    main()
