import os
import sys
import json

sys.path.append(os.path.join(os.getcwd(), "backend"))

from astroq.lk_prediction.pipeline import LKPredictionPipeline
from astroq.lk_prediction.config import ModelConfig
from astroq.lk_prediction.chart_generator import ChartGenerator

GEO_MAP = {
    "Allahabad, India": (25.4358, 81.8463, "+05:30"),
    "Mumbai, India": (19.0760, 72.8777, "+05:30"),
    "Vadnagar, India": (23.7801, 72.6373, "+05:30"),
    "San Francisco, California, US": (37.7749, -122.4194, "-08:00"),
    "Seattle, Washington, US": (47.6062, -122.3321, "-08:00"),
    "Sandringham, Norfolk, UK": (52.8311, 0.5054, "+00:00"),
    "New Delhi, India": (28.6139, 77.2090, "+05:30"),
    "Gary, Indiana, US": (41.5934, -87.3464, "-06:00"),
    "Pretoria, South Africa": (-25.7479, 28.2293, "+02:00"),
    "Porbandar, India": (21.6417, 69.6293, "+05:30"),
    "Raisen, India": (23.3308, 77.7788, "+05:30"),
    "Madanapalle, India": (13.5562, 78.5020, "+05:30"),
    "Indore, India": (22.7196, 75.8577, "+05:30"),
    "Jamshedpur, India": (22.8046, 86.2029, "+05:30"),
    "Jamaica Hospital, Queens, New York, US": (40.7028, -73.8152, "-05:00"),
    "Honolulu, Hawaii, US": (21.3069, -157.8583, "-10:00"),
    "Scranton, Pennsylvania, US": (41.4090, -75.6624, "-05:00"),
    "Mayfair, London, UK": (51.5100, -0.1458, "+00:00"),
    "Buckingham Palace, London, UK": (51.5014, -0.1419, "+00:00"),
    "Skopje, North Macedonia": (42.0003, 21.4280, "+01:00")
}

def verify_timing():
    cfg = ModelConfig(db_path="backend/data/rules.db", defaults_path="backend/data/defaults.json")
    pipeline = LKPredictionPipeline(cfg)
    generator = ChartGenerator()
    
    data_path = os.path.join("backend", "data", "public_figures_ground_truth.json")
    with open(data_path, "r") as f:
        figures = json.load(f)
        
    for fig in figures:
        name = fig["name"]
        events = fig.get("events", [])
        if not events: continue
        
        dob = fig["dob"]
        tob = fig["tob"]
        if len(tob.split(":")) == 2: tob += ":00"
        place = fig.get("birth_place", "New Delhi, India")
        lat, lon, tz = GEO_MAP.get(place, (28.6139, 77.2090, "+05:30"))
        
        print(f"\\n{'='*50}\\nAnalyzing {name}\\n{'='*50}")
        try:
            payload = generator.build_full_chart_payload(
                dob_str=dob, tob_str=tob, place_name=place, 
                latitude=lat, longitude=lon, utc_string=tz, chart_system="vedic"
            )
        except Exception as e:
            print(f"Error generating chart for {name}: {e}")
            continue
            
        charts = list(payload.values())
        report = pipeline.generate_full_payload(name, dob, charts)
        
        for event in events:
            age = event.get("age")
            domain = event.get("domain", "")
            desc = event.get("description", "")
            if not age: continue
            
            print(f"\\n  EVENT: {desc} (Age {age}, Domain: {domain})")
            
            # Check a window around the event
            for test_age in range(age - 2, age + 3):
                annual_data = next((y for y in report["annual_timeline"] if y["age"] == test_age), None)
                if not annual_data: continue
                
                marker = "⭐ EVENT YEAR ⭐" if test_age == age else "               "
                
                timing_signals = []
                for p_text in annual_data["predictions"]:
                    if "[HIGH]" in p_text or "[MEDIUM]" in p_text or "PROHIBITED" in p_text:
                        # Extract just the timing part
                        timing_signals.append(p_text)
                        
                if timing_signals:
                    print(f"    {marker} Age {test_age} | Pipeline Signals:")
                    for sig in timing_signals:
                        print(f"      -> {sig[:150]}...") # truncate for readability
                else:
                    if test_age == age:
                        print(f"    {marker} Age {test_age} | No explicit timing signals generated by pipeline.")

if __name__ == "__main__":
    verify_timing()
